apiVersion: v1
stringData:
  RHDH_URL: 
  SCAFFOLDER_BEARER_TOKEN: ""
  SOFTWARE_TEMPLATE_REF: template:default/hello-world-template
type: Opaque  
kind: Secret
metadata:
  name: software-template-workflow-secrets